name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Calculate version
        uses: app-swap/action-version@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          cat package.json
          pnpm build

      # - name: Publish
      #   uses: app-swap/action-version@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
      #     npm config set @appswap:registry=https://npm.appswap.dev/
      #     npm config set //npm.appswap.dev/:_authToken=${{ secrets.NPM_APPSWAP_DEV_TOKEN }}
      #     pnpm exec changeset publish
      #     git config --local user.name "github-actions[bot]"
      #     git config --local user.email "github-actions[bot]@users.noreply.github.com"
      #     git add .
      #     git commit -m "[ci skip] chore: release" || echo "No changes to commit"
      #     git push origin HEAD:${{ github.ref }}
      #     pnpm pack --out appswap-docs.tgz
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Calculate version
      #   uses: app-swap/action-version@v1
